### ISSUE TITLE
setup.py points to a file that does not exist

### ISSUE THREAD

**Issue by cmadrid1** [fizisist/LorentzGroupNetwork#1]
I was able to pip install after changing line 25 in setup.py with: README.rst -> README.md. In general this file has info from a different repository. 

Also, the README.md refers to a repo that does not exist:
`git clone git@github.com:fizisist/NBodyJetNets.git`
This `NBodyJetNets` directory is referenced a couple of times.

**Comment by abogatskiy** [comment]
I've fixed those references, they should point to `LorentzGroupNetwork` of course. Hopefully it works now.

**Comment by cmadrid1** [comment]
Thank you for the prompt response and correction. Also, the README references a directory named `NetworkDesign` that I am having trouble finding, and isn't obvious what it is used for.

**Comment by abogatskiy** [comment]
Thanks Chris, that should just be the root folder. I'll change that too. Some of the setup might depend on your local config, but feel free to let me know if you have further issues.
