### ISSUE TITLE
Import statement prevents lgn from importing correctly

### ISSUE THREAD

**Issue by DanDan0101** [fizisist/LorentzGroupNetwork#2]
In order for me to successfully `import lgn`, I needed to change import statements in `src/lgn/g_lib/g_torch.py`. Specifically, I needed to change line 2 from `import lgn.g_lib.rotations as rot` to `from lgn.g_lib import rotations as rot`, after which the import ran with no problems.

**Comment by janTOffermann** [comment]
Hi dan, thanks for bringing this to our attention!
So far I wasn't able to reproduce this error. I set up `lgn` with the following:
```
git clone https://github.com/fizisist/LorentzGroupNetwork.git
cd LorentzGroupNetwork
pip install .
```
after which point I was successfully able to run `import lgn`. Here are the relevant specs:
**OS**: Ubuntu 18.04.3 LTS
**Python version:** 3.7.6

Perhaps we might have set things up differently?

**Comment by DanDan0101** [comment]
I followed the exact same steps to install LGN (except installing it in `pip -e` mode, but that shouldn't matter ... I think), here are some possible differences:

- **OS:** Windows 10 Version 20H2
- **Python version:** 3.6.10 based in Anaconda

**Comment by janTOffermann** [comment]
I'm not 100% sure on what the cause might be -- but I've pushed the change you suggested to `master`, based on some of the other code in the repo I think this is the "canonical way" to do things.
