### ISSUE TITLE
Data file names

### ISSUE THREAD

**Issue by jacanchaplais** [fizisist/LorentzGroupNetwork#3]
Hi - I enjoyed the paper. :)

Spent a while unsuccessfully trying to get the code running with the dataset listed on Zenodo, then I realised by digging into the source that the data files must be called "train*", "test*" and "valid*". The dataset has the latter as "val.h5", so I was getting an error from pytorch about empty iterables (as the file wasn't found). Might be worth a mention in the docs about the naming convention.

Everything running smoothly now, though.

Thanks!
Jacan.

**Comment by janTOffermann** [comment]
Hi @jacanchaplais! Apologies for the delayed response.

Thanks for the catch -- indeed, we chose to make some assumptions about filenames, which I have added to the documentation. And I have changed the pattern for the validation to "val*.h5" to make sure that things are more consistent than before.
