### ISSUE TITLE
Issue with CGDict()

### ISSUE THREAD

**Issue by sam-cal** [fizisist/LorentzGroupNetwork#4]
Dear authors,

I gave  try to your nice code by running:
python manual_tests/cg_product_covariance.py
And I got the error:
gen_cg_dict called with maxdim = 3
Traceback (most recent call last):
  File "manual_tests/cg_product_covariance.py", line 41, in <module>
    cg_dict = CGDict(maxdim=maxdim)
  File "/AtlasDisk/user/scalvet/ML_py3.6/Lorentz/LorentzGroupNetwork/src/lgn/cg_lib/cg_dict.py", line 60, in __init__
    self.update_maxdim(maxdim)
  File "/AtlasDisk/user/scalvet/ML_py3.6/Lorentz/LorentzGroupNetwork/src/lgn/cg_lib/cg_dict.py", line 103, in update_maxdim
    cg_dict_new = {key: {irrep: cg_tens.view(-1, cg_tens.shape[-1]) for irrep, cg_tens in val.items()} for key, val in cg_dict_new.items()}
  File "/AtlasDisk/user/scalvet/ML_py3.6/Lorentz/LorentzGroupNetwork/src/lgn/cg_lib/cg_dict.py", line 103, in <dictcomp>
    cg_dict_new = {key: {irrep: cg_tens.view(-1, cg_tens.shape[-1]) for irrep, cg_tens in val.items()} for key, val in cg_dict_new.items()}
  File "/AtlasDisk/user/scalvet/ML_py3.6/Lorentz/LorentzGroupNetwork/src/lgn/cg_lib/cg_dict.py", line 103, in <dictcomp>
    cg_dict_new = {key: {irrep: cg_tens.view(-1, cg_tens.shape[-1]) for irrep, cg_tens in val.items()} for key, val in cg_dict_new.items()}
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

I changed the line 103 of src/lgn/cg_lib/cg_dict.py from : 
        cg_dict_new = {key: {irrep: cg_tens.view(-1, cg_tens.shape[-1]) for irrep, cg_tens in val.items()} for key, val in cg_dict_new.items()}
into
        cg_dict_new = {key: {irrep: cg_tens.reshape(-1, cg_tens.shape[-1]) for irrep, cg_tens in val.items()} for key, val in cg_dict_new.items()}
and the issue seems to be fixed.

Cheers,
Samuel

**Comment by abogatskiy** [comment]
Hi. Excuse my late reply. I believe this is a bug caused by a change in PyTorch made since this repo was published.  You can either try reverting PyTorch to 1.2 or so, or simply add `.contiguous()` right before every `.view()` that causes this error. I will also push a corresponding fix.

**Comment by abogatskiy** [comment]
Pushed an update, let me know if you still have issues.

**Comment by sam-cal** [comment]
I confirm it works now. Thanks!
